### ISSUE TITLE
KeyError: 'speaker_adversarial'

### ISSUE THREAD

**Issue by pavelxx1** [k2kobayashi/crank#26]
Hi, after your last update I have this error , when training:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/crank/crank/bin/train.py", line 179, in <module>
    main()
  File "/content/crank/crank/bin/train.py", line 134, in main
    model = get_model(conf, spkr_size, device)
  File "/content/crank/crank/bin/train.py", line 82, in get_model
    if conf["speaker_adversarial"]:
KeyError: 'speaker_adversarial'

**Comment by k2kobayashi** [comment]
Hi, I updated yml files.
