### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by pavelxx1** [k2kobayashi/crank#34]
```
# python -m crank.bin.extract_statistics --n_jobs 2 --phase train --conf conf/mlfb_vqvae.yml --scpdir data/scp --featdir data/feature 
# Started at Mon Dec  7 14:55:35 UTC 2020
#
INFO:root:# of samples for mlfb: 208496
INFO:root:# of samples for mcep: 208496
INFO:root:# of samples for lcf0: 208496
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/crank/crank/bin/extract_statistics.py", line 90, in <module>
    main()
  File "/content/crank/crank/bin/extract_statistics.py", line 79, in main
    "lcf0", spkr, s.ss.n_samples_seen_
AttributeError: 'StandardScaler' object has no attribute 'n_samples_seen_'
# Accounting: time=3 threads=1
# Ended (code 1) at Mon Dec  7 14:55:38 UTC 2020, elapsed time 3 seconds

```

**Comment by unilight** [comment]
Which dataset did you use? I ran into a similar issue too, and it turned out that one of the speakers did not have any training utterances. Maybe you can check `data/scp/train/spk2utt`.
