### ISSUE TITLE
KeyError "mcep"

### ISSUE THREAD

**Issue by misbullah** [k2kobayashi/crank#43]
Yesterday, I try to use the toolkit with my own dataset. However, I got the following error:

\# python -m crank.bin.extract_feature --n_jobs 10 --phase train --conf conf/mlfb_vqvae.yml --spkr_yml conf/spkr.yml --scpdir data/scp --featdir data/feature 
\# Started at Thu Mar 25 00:09:23 UTC 2021
\#
INFO:root:extract feature for Dysarthria_Taiwan_Moderate_CP_WuSH_VAD
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/alim/Crank/crank/crank/feature/feature.py", line 51, in analyze
    self._synthesize_world_features(flbl)
  File "/home/alim/Crank/crank/crank/feature/feature.py", line 115, in _synthesize_world_features
    self.feats["mcep"],
KeyError: 'mcep'

Any solution?

**Comment by unilight** [comment]
Hi @misbullah , what is the sampling rate of your custom dataset? According to https://github.com/k2kobayashi/crank/blob/master/crank/feature/feature.py#L89, if the sampling rate is lower than 16k then there would be some error when extracting world features so the current script does not do it. @k2kobayashi I think in the feature extractions stage, if we want to use `mlfb`, then we don't need to force to extract and synthesize world features. Maybe we can change it.

**Comment by misbullah** [comment]
Thanks a lot for quick response.

Currently, the sampling rate for my dataset is 16kHz. How to change the configuration so that it can be run?

It also get error when I use `mcep`.
.
Thanks a lot.

**Comment by unilight** [comment]
You can try to comment https://github.com/k2kobayashi/crank/blob/master/crank/feature/feature.py#L89 off and see what happens.

**Comment by misbullah** [comment]
Hi, I tried to comment the line 89 but it seems does not work. 

Maybe is there any suggestion?

**Comment by unilight** [comment]
I cannot help you if you don't provide any further information.

**Comment by misbullah** [comment]
Sorry @unilight. The following is the error after I comment L89 of feature.py

INFO:root:# of samples for mlfb: 1021248
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alim/Crank/crank/crank/bin/extract_statistics.py", line 94, in <module>
    main()
  File "/home/alim/Crank/crank/crank/bin/extract_statistics.py", line 72, in main
    s.fit(list(scp["feats"].values()), ext=ext)
  File "/home/alim/Crank/crank/crank/bin/extract_statistics.py", line 37, in fit
    data = fp[ext][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'lcf0' doesn't exist)"

Thanks a lot for your help.

**Comment by misbullah** [comment]
Any solution about the error?

**Comment by misbullah** [comment]
Hi @unilight,

The feature can be extracted now from 16kHz. But when the step goes to training, it shows the following error:

  File "/home/alim/Crank/crank/crank/net/trainer/basetrainer.py", line 154, in _tr_step
    for batch in self.dataloader["train"]:
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/alim/Crank/crank/crank/net/trainer/dataset.py", line 62, in __getitem__
    sample = self._middle_getitem(sample)
  File "/home/alim/Crank/crank/crank/net/trainer/dataset.py", line 113, in _middle_getitem
    sample = self._zero_padding(sample)
  File "/home/alim/Crank/crank/crank/net/trainer/dataset.py", line 175, in _zero_padding
    sample[k] = padding(v, dlen, self.batch_len, value=0.0, p=p).astype(
  File "/home/alim/Crank/crank/crank/net/trainer/dataset.py", line 230, in padding
    x = np.concatenate([x, np.ones((actual_dlen, x.shape[1])) * value])
  File "/home/alim/Crank/crank/tools/venv/lib/python3.6/site-packages/numpy/core/numeric.py", line 207, in ones
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed

Do you have any suggestion about the issue?

Thanks for help.

**Comment by unilight** [comment]
Hi @misbullah, sorry I have never encountered this error before. From the error log, I can only guess that `actual_dlen` might have mistakenly become negative. Can you try to print that variable and see what happened?

**Comment by misbullah** [comment]
Hi @unilight 

I found the solution when I use 16kHz 

I changed this config:

batch_len: 500           # frame length (time_axis) of a mini-batch

to be

batch_len: 100           # frame length (time_axis) of a mini-batch

It works now.

Thanks
