### ISSUE TITLE
unlink() got an unexpected keyword argument 'missing_ok

### ISSUE THREAD

**Issue by unilight** [k2kobayashi/crank#5]
During stage 2, I got the following error in `data/log/extract_feature_train.log`:
```
Traceback (most recent call last):
  File "/home/huang18/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/huang18/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nas01/internal/wenchin-h/VC/Experiments/crank/crank/bin/extract_feature.py", line 75, in <module>
    main()
  File "/nas01/internal/wenchin-h/VC/Experiments/crank/crank/bin/extract_feature.py", line 42, in main
    (featsscp).unlink(missing_ok=True)
TypeError: unlink() got an unexpected keyword argument 'missing_ok'
```
According to https://docs.python.org/3/library/pathlib.html#pathlib.Path.unlink, this new parameter seems to be new in Python 3.8. Is it possible to make it compatible to lower python versions?

**Comment by k2kobayashi** [comment]
Sure. I modified it.
